name: Test

on:
  push:
    branches-ignore: [main]

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Typecheck files
        run: |
          yarn typecheck

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [typecheck]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Lint files
        run: |
          yarn lint

  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Unit test files
        run: |
          yarn test:unit

  integration_test:
    name: Integration Test
    runs-on: ubuntu-latest
    needs: [unit_test]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Integration test files
        run: |
          yarn test:integration
